version: 2.1
workflows:
  workflow:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/arcadia

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn

      - run:
          name: Build app
          command: yarn build

      - deploy:
          name: Deploy to S3
          command: yarn deploy
